controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:
      type: position_controllers/JointGroupPositionController


position_controllers:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - hip_fl
      - shoulder_fl
      - knee_fl
      - hip_fr
      - shoulder_fr
      - knee_fr
      - hip_bl
      - shoulder_bl
      - knee_bl
      - hip_br
      - shoulder_br
      - knee_br
    command_interfaces:
      - position
    state_interfaces:
      - position
  