# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    BL_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    BR_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    FL_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    FR_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

BL_controller:
  ros__parameters:
    joints:
      - hip_bl
      - shoulder_bl
      - knee_bl
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
BR_controller:
  ros__parameters:
    joints:
      - hip_br
      - shoulder_br
      - knee_br
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
FL_controller:
  ros__parameters:
    joints:
      - hip_fl
      - shoulder_fl
      - knee_fl
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
FR_controller:
  ros__parameters:
    joints:
      - hip_fr
      - shoulder_fr
      - knee_fr
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity